version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    ports:
      - "6011:6011"
      - "6012:6012"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: Admin123
    volumes:
      - demo-objectstorage-volume:/data
    command: server /data --console-address ":6011"
    restart: unless-stopped
    networks:
      - demo-Intelli-chat
  
volumes:
  demo-objectstorage-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-objectstorage-volume
      o: bind

networks:
  demo-Intelli-chat:
    external: true