version: "3.12"

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:4000"
    
    environment:
      - OPENAI_API_KEY="sk_biuk5L0-NzYh5QoDl_vZSwHr0RxOJibZLXcGFlbyTqM"
    command: --config /app/config.yaml

networks:
  demo-Intelli-chat:
    driver: bridge
    external: true