version: "3.12"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: litellmdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-Intelli-chat
    restart: unless-stopped
    command: ["postgres", "-p", "5432"]

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - LITELLM_MASTER_KEY=litellm123
      - UI_USERNAME=admin
      - UI_PASSWORD=admin123123
      - OPENAI_API_KEY=""
      - DATABASE_URL=postgresql://admin:admin123123@postgres:5432/litellmdb
    command: --config /app/config.yaml
  

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-postgresql-volume
      o: bind

networks:
  demo-Intelli-chat:
    driver: bridge
    external: true
