version: '3.8'

services:

  qdrant:
    container_name: demo-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6003:6333"
    volumes:
      - demo-qdrant-volume:/qdrant/storage
    configs:
      - source: qdrant-config
        target: /qdrant/config/production.yaml
    networks:
      - demo-Intelli-chat
    restart: unless-stopped

  redis:
    container_name: demo-redis
    image: redis:latest
    ports:
      - "6001:6379"
    volumes:
      - demo-redis-volume:/data
    networks:
      - demo-Intelli-chat
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sale
    ports:
      - "6000:5432"
    volumes:
      - demo-postgresql-volume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - demo-Intelli-chat

volumes:
  demo-graphdb-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-graphdb-volume
      o: bind

  demo-qdrant-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-qdrant-volume
      o: bind

  demo-redis-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-redis-volume
      o: bind

  demo-postgresql-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/demo-postgresql-volume
      o: bind

  demo-lightrag-ragstorage-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/lightrag/data/rag_storage
      o: bind

  demo-lightrag-inputs-volume:
    driver: local
    driver_opts:
      type: none
      device: /opt/shared/intelli-chat/lightrag/data/inputs
      o: bind

networks:
  demo-Intelli-chat:
    driver: bridge
    external: true

configs:
  qdrant-config:
    file: /opt/shared/intelli-chat/qdrant_config/production.yaml